# run Cypress tests using CircleCI Cypress orb
# https://github.com/cypress-io/circleci-orb
# Circle CI API token | mgmri | 2ab815f3fb0bd85697ffc9dde564cbf980b9b484

version: 2.1
orbs:
  cypress: cypress-io/cypress@1.5.1

executors:
  mac:
    macos:
      xcode: "10.1.0"
  linux:
    machine:
      enabled: true

jobs:
  lint:
    executor: cypress/base-10
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run types
      - run: npm run lint
  circleCiTest:
    executor: linux
    steps:
      - run: 'curl -X POST --header "Content-Type: application/json" -d {"branch":"master"} https://circleci.com/api/v1.1/project/github/alffrey/dmp-cypress-e2e/build?circle-token=2ab815f3fb0bd85697ffc9dde564cbf980b9b484'

workflows:
  build:
    jobs:
      - cypress/run:
          name: Linux test
          start: npm start
      - cypress/run:
          name: Mac test
          executor: mac
          start: npm start
      - lint:
          requires:
            - Linux test
      - circleCiTest:
          requires:
            - Linux test
          
